name: Add 404.html to WeWeb export

on:
  push:
    branches:
      - staging

permissions:
  contents: write

jobs:
  add-404:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create 404.html
        run: |
          mkdir -p public
          cp public/index.html public/404.html || echo "index.html not found"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/404.html
          git commit -m "add 404.html fallback" || echo "no changes"
          git push
