name: Move vercel.json to root

on:
  push:
    branches:
      - staging  # Trigger auf Pushes im Staging-Branch

jobs:
  move-file:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Move vercel.json to root
        run: |
          mv public/vercel.json vercel.json

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add vercel.json
          git commit -m 'Move vercel.json to root' || echo "No changes to commit"
          git push origin HEAD:staging
