name: Sync WeWeb Export to `staging` Branch in `webapp/`

on:
  push:
    branches:
      - export

jobs:
  sync-to-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout `export` branch
        uses: actions/checkout@v4
        with:
          ref: export
          path: export

      - name: Checkout `staging` branch
        uses: actions/checkout@v4
        with:
          ref: staging
          path: staging

      - name: Clear old webapp/ and copy new export
        run: |
          rm -rf staging/webapp/*
          cp -r export/* staging/webapp/

      - name: Commit and push to `staging`
        run: |
          cd staging
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add webapp/
          git commit -m "🔄 Update webapp/ from export" || echo "No changes to commit"
          git push origin staging
