name: Create foo.bar

on:
  push:
    branches:
      - main
      - master
      - staging   # nimm raus, was du nicht brauchst

permissions:
  contents: write

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create file (visible in workspace)
        run: |
          mkdir -p src
          printf "Hello\nWorld\n" > src/foo.bar
          echo "=== ls -la src ==="
          ls -la src

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          echo "=== git status BEFORE add ==="
          git status --porcelain

          git add src/foo.bar

          echo "=== git status AFTER add ==="
          git status --porcelain

          # Commit nur, wenn es wirklich Änderungen gibt
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "chore: add src/foo.bar via workflow"

          # Push auf denselben Branch, auf dem der Workflow läuft
          CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          echo "Pushing to $CURRENT_BRANCH"
          git push origin "$CURRENT_BRANCH"

      - name: Show last commit
        run: |
          git --no-pager log -1 --stat
