name: Create A File

on:
  push:
    branches:
      - master   # ggf. auf 'main' ändern

permissions:
  contents: write   # wichtig für den Push

jobs:
  createFile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure target directory
        run: mkdir -p src

      - name: Create file
        uses: 1arp/create-a-file-action@0.4.5
        with:
          path: 'src'
          isAbsolutePath: false
          file: 'foo.bar'
          content: |
            Hello
            World

      - name: Commit & push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'src/foo.bar'
          message: 'chore: add foo.bar via workflow'
          default_author: github_actions
          push: true
