name: Ensure vercel.json on staging

on:
  push:
    branches:
      - staging   # << läuft nur bei Push auf staging

permissions:
  contents: write

jobs:
  ensure-config:
    # verhindert Endlosschleife, wenn der Bot selbst committed
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest

    # falls Vercel ein Root Directory nutzt (z. B. "site"), hier anpassen
    env:
      VERCEL_ROOT: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Ensure vercel.json (SPA fallback)
        shell: bash
        run: |
          ROOT="${VERCEL_ROOT:-.}"
          mkdir -p "$ROOT"
          cat > "$ROOT/vercel.json" <<'JSON'
{
  "$schema": "https://openapi.vercel.sh/vercel.json",
  "rewrites": [
    {
      "source": "/((?!.*\\.(?:png|jpg|jpeg|gif|svg|webp|ico|css|js|map|txt|xml|json|mp4|webm|wav|mp3|woff|woff2|ttf|otf)$).*)",
      "destination": "/index.html"
    }
  ]
}
JSON

      - name: Commit changes if needed
        shell: bash
        run: |
          if ! git diff --quiet; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(ci): ensure vercel.json on staging [skip ci]"
            git push
          else
            echo "No changes."
          fi
